function mor = morris_analyze(Xn, Y, k, r, delta)
% Compute elementary effects, mu*, sigma for each response column of Y.
% Xn: N x k (normalized), Y: N x m
% Assumes Xn generated by morris_design with r trajectories.

[N, k2] = size(Xn);
if k2 ~= k
    error("k mismatch");
end
if N ~= r*(k+1)
    error("Row count mismatch: expected %d rows from r*(k+1), got %d.", r*(k+1), N);
end
m = size(Y,2);

EE = NaN(r, k, m); % trajectory, variable, response

idx = 1;
for t = 1:r
    Xt = Xn(idx:idx+k, :);
    Yt = Y(idx:idx+k, :);

    % For each step, identify which variable changed
    for step = 1:k
        dx = Xt(step+1,:) - Xt(step,:);
        changed = find(abs(dx) > 1e-12);
        if numel(changed) ~= 1
            error("Invalid Morris step in trajectory %d, step %d (changed vars=%d).", t, step, numel(changed));
        end

        j = changed(1);
        stepSize = dx(j);
        if abs(abs(stepSize) - delta) > 1e-8
            warning("Step size %.6f differs from expected delta %.6f (trajectory %d, step %d).", stepSize, delta, t, step);
        end

        EE(t,j,:) = (Yt(step+1,:) - Yt(step,:)) / stepSize;
    end
    idx = idx + (k+1);
end

mu = squeeze(mean(EE,1,'omitnan'));              % k x m
mu_star = squeeze(mean(abs(EE),1,'omitnan'));    % k x m
sigma = squeeze(std(EE,0,1,'omitnan'));          % k x m

mor.EE = EE;
mor.mu = mu;
mor.mu_star = mu_star;
mor.sigma = sigma;
end