function mor = morris_analyze(Xn, Y, k, r, delta)
% Compute elementary effects, mu*, sigma for each response column of Y
% Xn: N x k (normalized), Y: N x m
% Assumes Xn generated by morris_design with r trajectories

[N, k2] = size(Xn);
if k2 ~= k
    error("k mismatch");
end
m = size(Y,2);

EE = NaN(r, k, m); % trajectory, variable, response

idx = 1;
for t = 1:r
    Xt = Xn(idx:idx+k, :);
    Yt = Y(idx:idx+k, :);

    % For each step, identify which variable changed
    for step = 1:k
        dx = Xt(step+1,:) - Xt(step,:);
        [~, j] = max(abs(dx));
        EE(t,j,:) = (Yt(step+1,:) - Yt(step,:)) / delta;
    end
    idx = idx + (k+1);
end

mu = squeeze(mean(EE,1,'omitnan'));              % k x m
mu_star = squeeze(mean(abs(EE),1,'omitnan'));    % k x m
sigma = squeeze(std(EE,0,1,'omitnan'));          % k x m

mor.EE = EE;
mor.mu = mu;
mor.mu_star = mu_star;
mor.sigma = sigma;
end
